# Generated by Django 6.0.8 on 2026-08-18 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('description', models.TextField(max_length=600)),
                ('primary_badge', models.CharField(choices=[('ai-made', 'AI-MADE'), ('ai-assisted', 'AI-ASSISTED'), ('ai-edited', 'AI-EDITED'), ('no-generative-ai', 'NO GENERATIVE AI'), ('no-ai-used', 'NO AI USED')], max_length=30)),
                ('qualifiers', models.JSONField(blank=True, default=list)),
                ('tools_used', models.CharField(blank=True, help_text='Optional — e.g. ChatGPT, Midjourney, no AI tools', max_length=300)),
                ('process_note', models.TextField(blank=True, max_length=800)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
