# Generated by Django 6.0.8 on 2026-08-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledgeacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='pledge_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
