# Generated by Django 6.0.8 on 2026-08-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_magiclink_pledge_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='code_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
