# Generated by Django 6.0.8 on 2026-08-21 16:32

from django.db import migrations


def remove_public_accounts(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(is_superuser=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_adhesion_comment_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclink',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='pledgeacceptance',
            name='unique_pledge_acceptance',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MagicLink',
        ),
        migrations.RemoveField(
            model_name='pledgeacceptance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='PledgeAcceptance',
        ),
        migrations.RunPython(remove_public_accounts, migrations.RunPython.noop),
    ]
